### ISSUE TITLE
Add .akira.yml

### ISSUE THREAD

**Issue by dennishn** [nodes-frontend/generator-nodes#3]
Example:

```
project:
    name: working-local-co
    type: angular

prepare:

config:

docker_template: "clean-default"
```

Must be automatically filled with project name on scaffolding
